name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_NO_CLOUD: 'true'
      NX_DAEMON: 'false'
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci

      - run: npx playwright install --only-shell

      - run: npx nx affected -t lint test build typecheck --parallel=3 --base=origin/main~1 --head=HEAD

      - run: npx nx affected -t e2e --parallel=1 --base=origin/main~1 --head=HEAD
